export default [
  {
    name: 'name',
    label: 'שם קרן',
    field: 'FUND_NAME',
    sortable: true,
    align: 'left',
  },
  {
    name: 'name',
    label: 'סוג קרן',
    field: 'FUND_CLASSIFICATION',
    sortable: true,
    align: 'left',
  },
  {
    name: 'name',
    label: 'חברה',
    field: 'MANAGING_CORPORATION',
    sortable: true,
    align: 'left',
  },
  {
    name: 'name',
    label: 'מדד שארפ',
    field: 'SHARPE_RATIO',
    sortable: true,
    align: 'left',
  },
];
// MANAGING_CORPORATION: 'הראל פנסיה וגמל בע"מ',
// REPORT_PERIOD: '202201',
// INCEPTION_DATE: '4/1/1979 12:00:00 AM',
// TARGET_POPULATION: 'כלל האוכלוסיה',
// SPECIALIZATION: 'אג"ח',
// SUB_SPECIALIZATION: 'משולב מניות',
// DEPOSITS: '23.17',
// WITHDRAWLS: '38.26',
// INTERNAL_TRANSFERS: '-32.64',
// NET_MONTHLY_DEPOSITS: '-47.73',
// TOTAL_ASSETS: '9591.23',
// AVG_ANNUAL_MANAGEMENT_FEE: '0.65',
// AVG_DEPOSIT_FEE: '0.32',
// MONTHLY_YIELD: '-1.44',
// YEAR_TO_DATE_YIELD: '-1.44',
// YIELD_TRAILING_3_YRS: '21.89',
// YIELD_TRAILING_5_YRS: '30.73',
// AVG_ANNUAL_YIELD_TRAILING_3YRS: '6.82',
// AVG_ANNUAL_YIELD_TRAILING_5YRS: '5.51',
// STANDARD_DEVIATION: '4.69',
// ALPHA: '0.84',
// SHARPE_RATIO: '1.19',
// LIQUID_ASSETS_PERCENT: '74',
// STOCK_MARKET_EXPOSURE: '2328.95',
// FOREIGN_EXPOSURE: '3183.72',
// FOREIGN_CURRENCY_EXPOSURE: '1534.49',
// MANAGING_CORPORATION_LEGAL_ID: '512267592',
// CURRENT_DATE: '5/14/2022 12:00:00 AM',
