import type { TreeNode } from '../types';

export const onlyDashboardsData: TreeNode = {
	owner: {
		_id: '6095c108c59972001a487fa6',
		firstName: 'Test',
		lastName: 'Test',
		email: 'admin@sisense.com',
	},
	instanceType: 'owner',
	oid: 'rootFolder',
	name: 'rootFolder',
	type: 'folder',
	dashboards: [
		{
			title: 'Sample - Ecommerce',
			shares: [
				{
					shareId: '6095c108c59972001a487fa6',
					type: 'user',
				},
			],
			owner: {
				_id: '6095c108c59972001a487fa6',
				firstName: 'Test',
				lastName: 'Test',
				email: 'admin@sisense.com',
			},
			created: '2021-08-29T10:04:28.375Z',
			lastUpdated: '2021-12-15T08:45:44.034Z',
			instanceType: 'owner',
			datasource: {
				title: 'Sample ECommerce',
				id: 'localhost_aSampleIAAaECommerce',
				address: 'LocalHost',
				database: 'aSampleIAAaECommerce',
			},
			oid: '612b5bac7e2d3200362aac05',
			parentFolder: null,
			lastOpened: '2021-12-15T08:34:22.633Z',
			widgets: [],
			_dataSourcePermission: 'owner',
			userAuth: {
				dashboards: {
					create: true,
					delete: true,
					move: true,
					rename: true,
					duplicate: true,
					change_owner: true,
					toggle_edit_mode: true,
					edit_layout: true,
					edit_script: true,
					export_dash: true,
					export_jpeg: true,
					export_image: true,
					export_pdf: true,
					share: true,
					restore: true,
					copy_to_server: true,
					import: true,
					select_palette: true,
					replace_datasource: true,
					undo_import_dash: true,
					toggleDataExploration: true,
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						reorder: true,
						modify_type: true,
						toggle_auto_update: true,
						set_defaults: true,
						advanced: true,
						use_starred: true,
					},
				},
				widgets: {
					create: true,
					delete: true,
					rename: true,
					duplicate: true,
					copy_to_dashboard: true,
					edit: true,
					edit_script: true,
					change_type: true,
					export_csv: true,
					export_png: true,
					export_svg: true,
					export_pdf: true,
					modify_selection_attrs: true,
					modify_selection_mode: true,
					drill_to_anywhere: true,
					add_to_pulse: true,
					items: {
						create: true,
						delete: true,
						rename: true,
						modify: true,
						reorder: true,
						modify_type: true,
						modify_format: true,
						on_off: true,
						select_hierarchies: true,
					},
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						modify_layout: true,
						modify_type: true,
						modify_dashboard_filters: true,
						use_starred: true,
					},
					widgetViewOnly: false,
				},
				base: {
					isConsumer: false,
					isContributor: false,
					isAdmin: false,
					isSuper: true,
				},
			},
		},
		{
			title: 'Sample ECommerce - Tuan Test',
			shares: [
				{
					shareId: '6095c108c59972001a487fa6',
					type: 'user',
				},
			],
			owner: {
				_id: '6095c108c59972001a487fa6',
				firstName: 'Test',
				lastName: 'Test',
				email: 'admin@sisense.com',
			},
			created: '2021-10-29T16:02:48.303Z',
			lastUpdated: '2021-12-12T09:19:20.517Z',
			instanceType: 'owner',
			oid: '617c1b2810e87300363cd435',
			lastOpened: '2021-12-15T08:34:21.879Z',
			datasource: {
				fullname: 'localhost/Sample ECommerce',
				id: 'localhost_aSampleIAAaECommerce',
				address: 'LocalHost',
				database: 'aSampleIAAaECommerce',
				live: false,
				title: 'Sample ECommerce',
			},
			parentFolder: null,
			userAuth: {
				dashboards: {
					create: true,
					delete: true,
					move: true,
					rename: true,
					duplicate: true,
					change_owner: true,
					toggle_edit_mode: true,
					edit_layout: true,
					edit_script: true,
					export_dash: true,
					export_jpeg: true,
					export_image: true,
					export_pdf: true,
					share: true,
					restore: true,
					copy_to_server: true,
					import: true,
					select_palette: true,
					replace_datasource: true,
					undo_import_dash: true,
					toggleDataExploration: true,
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						reorder: true,
						modify_type: true,
						toggle_auto_update: true,
						set_defaults: true,
						advanced: true,
						use_starred: true,
					},
				},
				widgets: {
					create: true,
					delete: true,
					rename: true,
					duplicate: true,
					copy_to_dashboard: true,
					edit: true,
					edit_script: true,
					change_type: true,
					export_csv: true,
					export_png: true,
					export_svg: true,
					export_pdf: true,
					modify_selection_attrs: true,
					modify_selection_mode: true,
					drill_to_anywhere: true,
					add_to_pulse: true,
					items: {
						create: true,
						delete: true,
						rename: true,
						modify: true,
						reorder: true,
						modify_type: true,
						modify_format: true,
						on_off: true,
						select_hierarchies: true,
					},
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						modify_layout: true,
						modify_type: true,
						modify_dashboard_filters: true,
						use_starred: true,
					},
					widgetViewOnly: false,
				},
				base: {
					isConsumer: false,
					isContributor: false,
					isAdmin: false,
					isSuper: true,
				},
			},
		},
		{
			title: 'Sample Healthcare (1)',
			oid: '6180040294078e003665c83f',
			shares: [
				{
					shareId: '6095c108c59972001a487fa6',
					type: 'user',
				},
			],
			owner: {
				_id: '6095c108c59972001a487fa6',
				firstName: 'Test',
				lastName: 'Test',
				email: 'admin@sisense.com',
			},
			created: '2021-11-01T15:13:06.194Z',
			lastUpdated: '2021-11-01T15:13:09.230Z',
			instanceType: 'owner',
			lastOpened: '2021-12-13T09:25:49.966Z',
			datasource: {
				fullname: 'localhost/Sample Healthcare',
				id: 'localhost_aSampleIAAaHealthcare',
				address: 'LocalHost',
				database: 'aSampleIAAaHealthcare',
				live: false,
				title: 'Sample Healthcare',
			},
			userAuth: {
				dashboards: {
					create: true,
					delete: true,
					move: true,
					rename: true,
					duplicate: true,
					change_owner: true,
					toggle_edit_mode: true,
					edit_layout: true,
					edit_script: true,
					export_dash: true,
					export_jpeg: true,
					export_image: true,
					export_pdf: true,
					share: true,
					restore: true,
					copy_to_server: true,
					import: true,
					select_palette: true,
					replace_datasource: true,
					undo_import_dash: true,
					toggleDataExploration: true,
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						reorder: true,
						modify_type: true,
						toggle_auto_update: true,
						set_defaults: true,
						advanced: true,
						use_starred: true,
					},
				},
				widgets: {
					create: true,
					delete: true,
					rename: true,
					duplicate: true,
					copy_to_dashboard: true,
					edit: true,
					edit_script: true,
					change_type: true,
					export_csv: true,
					export_png: true,
					export_svg: true,
					export_pdf: true,
					modify_selection_attrs: true,
					modify_selection_mode: true,
					drill_to_anywhere: true,
					add_to_pulse: true,
					items: {
						create: true,
						delete: true,
						rename: true,
						modify: true,
						reorder: true,
						modify_type: true,
						modify_format: true,
						on_off: true,
						select_hierarchies: true,
					},
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						modify_layout: true,
						modify_type: true,
						modify_dashboard_filters: true,
						use_starred: true,
					},
					widgetViewOnly: false,
				},
				base: {
					isConsumer: false,
					isContributor: false,
					isAdmin: false,
					isSuper: true,
				},
			},
		},
		{
			title: "Mia's Dashboard",
			oid: '61940d57ca6ca30036c7a6a5',
			shares: [
				{
					shareId: '6095c108c59972001a487fa6',
					type: 'user',
				},
			],
			owner: {
				_id: '6095c108c59972001a487fa6',
				firstName: 'Test',
				lastName: 'Test',
				email: 'admin@sisense.com',
			},
			created: '2021-11-16T19:58:15.459Z',
			lastUpdated: '2021-12-15T08:10:52.806Z',
			instanceType: 'owner',
			lastOpened: '2021-12-15T13:47:50.403Z',
			datasource: {
				fullname: 'live:Mia',
				id: 'live:Mia',
				live: true,
				title: 'Mia',
			},
			parentFolder: null,
			userAuth: {
				dashboards: {
					create: true,
					delete: true,
					move: true,
					rename: true,
					duplicate: true,
					change_owner: true,
					toggle_edit_mode: true,
					edit_layout: true,
					edit_script: true,
					export_dash: true,
					export_jpeg: true,
					export_image: true,
					export_pdf: true,
					share: true,
					restore: true,
					copy_to_server: true,
					import: true,
					select_palette: true,
					replace_datasource: true,
					undo_import_dash: true,
					toggleDataExploration: true,
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						reorder: true,
						modify_type: true,
						toggle_auto_update: true,
						set_defaults: true,
						advanced: true,
						use_starred: true,
					},
				},
				widgets: {
					create: true,
					delete: true,
					rename: true,
					duplicate: true,
					copy_to_dashboard: true,
					edit: true,
					edit_script: true,
					change_type: true,
					export_csv: true,
					export_png: true,
					export_svg: true,
					export_pdf: true,
					modify_selection_attrs: true,
					modify_selection_mode: true,
					drill_to_anywhere: true,
					add_to_pulse: true,
					items: {
						create: true,
						delete: true,
						rename: true,
						modify: true,
						reorder: true,
						modify_type: true,
						modify_format: true,
						on_off: true,
						select_hierarchies: true,
					},
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						modify_layout: true,
						modify_type: true,
						modify_dashboard_filters: true,
						use_starred: true,
					},
					widgetViewOnly: false,
				},
				base: {
					isConsumer: false,
					isContributor: false,
					isAdmin: false,
					isSuper: true,
				},
			},
		},
		{
			title: 'Steven Sample ECommerce',
			shares: [
				{
					shareId: '6095c108c59972001a487fa6',
					type: 'user',
				},
			],
			owner: {
				_id: '6095c108c59972001a487fa6',
				firstName: 'Test',
				lastName: 'Test',
				email: 'admin@sisense.com',
			},
			created: '2021-11-24T16:07:20.878Z',
			lastUpdated: '2021-11-24T16:07:20.878Z',
			instanceType: 'owner',
			oid: '619e6338f341bc0037f5b2ef',
			datasource: {
				fullname: 'localhost/Sample ECommerce',
				id: 'localhost_aSampleIAAaECommerce',
				address: 'LocalHost',
				database: 'aSampleIAAaECommerce',
				live: false,
				title: 'Sample ECommerce',
			},
			lastPublish: '2021-08-10T21:21:09.667Z',
			parentFolder: null,
			allowChangeSubscription: false,
			lastOpened: '2021-12-12T09:09:40.076Z',
			userAuth: {
				dashboards: {
					create: true,
					delete: true,
					move: true,
					rename: true,
					duplicate: true,
					change_owner: true,
					toggle_edit_mode: true,
					edit_layout: true,
					edit_script: true,
					export_dash: true,
					export_jpeg: true,
					export_image: true,
					export_pdf: true,
					share: true,
					restore: true,
					copy_to_server: true,
					import: true,
					select_palette: true,
					replace_datasource: true,
					undo_import_dash: true,
					toggleDataExploration: true,
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						reorder: true,
						modify_type: true,
						toggle_auto_update: true,
						set_defaults: true,
						advanced: true,
						use_starred: true,
					},
				},
				widgets: {
					create: true,
					delete: true,
					rename: true,
					duplicate: true,
					copy_to_dashboard: true,
					edit: true,
					edit_script: true,
					change_type: true,
					export_csv: true,
					export_png: true,
					export_svg: true,
					export_pdf: true,
					modify_selection_attrs: true,
					modify_selection_mode: true,
					drill_to_anywhere: true,
					add_to_pulse: true,
					items: {
						create: true,
						delete: true,
						rename: true,
						modify: true,
						reorder: true,
						modify_type: true,
						modify_format: true,
						on_off: true,
						select_hierarchies: true,
					},
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						modify_layout: true,
						modify_type: true,
						modify_dashboard_filters: true,
						use_starred: true,
					},
					widgetViewOnly: false,
				},
				base: {
					isConsumer: false,
					isContributor: false,
					isAdmin: false,
					isSuper: true,
				},
			},
		},
		{
			title: 'Steven Sample ECommerce (1)',
			shares: [
				{
					shareId: '6095c108c59972001a487fa6',
					type: 'user',
				},
			],
			owner: {
				_id: '6095c108c59972001a487fa6',
				firstName: 'Test',
				lastName: 'Test',
				email: 'admin@sisense.com',
			},
			created: '2021-11-24T16:07:26.326Z',
			lastUpdated: '2021-11-24T16:07:26.326Z',
			instanceType: 'owner',
			oid: '619e633ef341bc0037f5b2f4',
			datasource: {
				fullname: 'localhost/Sample ECommerce',
				id: 'localhost_aSampleIAAaECommerce',
				address: 'LocalHost',
				database: 'aSampleIAAaECommerce',
				live: false,
				title: 'Sample ECommerce',
			},
			lastPublish: '2021-08-10T21:21:09.667Z',
			parentFolder: null,
			allowChangeSubscription: false,
			lastOpened: null,
			userAuth: {
				dashboards: {
					create: true,
					delete: true,
					move: true,
					rename: true,
					duplicate: true,
					change_owner: true,
					toggle_edit_mode: true,
					edit_layout: true,
					edit_script: true,
					export_dash: true,
					export_jpeg: true,
					export_image: true,
					export_pdf: true,
					share: true,
					restore: true,
					copy_to_server: true,
					import: true,
					select_palette: true,
					replace_datasource: true,
					undo_import_dash: true,
					toggleDataExploration: true,
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						reorder: true,
						modify_type: true,
						toggle_auto_update: true,
						set_defaults: true,
						advanced: true,
						use_starred: true,
					},
				},
				widgets: {
					create: true,
					delete: true,
					rename: true,
					duplicate: true,
					copy_to_dashboard: true,
					edit: true,
					edit_script: true,
					change_type: true,
					export_csv: true,
					export_png: true,
					export_svg: true,
					export_pdf: true,
					modify_selection_attrs: true,
					modify_selection_mode: true,
					drill_to_anywhere: true,
					add_to_pulse: true,
					items: {
						create: true,
						delete: true,
						rename: true,
						modify: true,
						reorder: true,
						modify_type: true,
						modify_format: true,
						on_off: true,
						select_hierarchies: true,
					},
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						modify_layout: true,
						modify_type: true,
						modify_dashboard_filters: true,
						use_starred: true,
					},
					widgetViewOnly: false,
				},
				base: {
					isConsumer: false,
					isContributor: false,
					isAdmin: false,
					isSuper: true,
				},
			},
		},
		{
			title: 'Steven Sample ECommerce (2)',
			shares: [
				{
					shareId: '6095c108c59972001a487fa6',
					type: 'user',
				},
			],
			owner: {
				_id: '6095c108c59972001a487fa6',
				firstName: 'Test',
				lastName: 'Test',
				email: 'admin@sisense.com',
			},
			created: '2021-11-24T16:07:29.316Z',
			lastUpdated: '2021-11-24T16:07:29.316Z',
			instanceType: 'owner',
			oid: '619e6341f341bc0037f5b2f9',
			datasource: {
				fullname: 'localhost/Sample ECommerce',
				id: 'localhost_aSampleIAAaECommerce',
				address: 'LocalHost',
				database: 'aSampleIAAaECommerce',
				live: false,
				title: 'Sample ECommerce',
			},
			lastPublish: '2021-08-10T21:21:09.667Z',
			parentFolder: null,
			allowChangeSubscription: false,
			lastOpened: null,
			userAuth: {
				dashboards: {
					create: true,
					delete: true,
					move: true,
					rename: true,
					duplicate: true,
					change_owner: true,
					toggle_edit_mode: true,
					edit_layout: true,
					edit_script: true,
					export_dash: true,
					export_jpeg: true,
					export_image: true,
					export_pdf: true,
					share: true,
					restore: true,
					copy_to_server: true,
					import: true,
					select_palette: true,
					replace_datasource: true,
					undo_import_dash: true,
					toggleDataExploration: true,
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						reorder: true,
						modify_type: true,
						toggle_auto_update: true,
						set_defaults: true,
						advanced: true,
						use_starred: true,
					},
				},
				widgets: {
					create: true,
					delete: true,
					rename: true,
					duplicate: true,
					copy_to_dashboard: true,
					edit: true,
					edit_script: true,
					change_type: true,
					export_csv: true,
					export_png: true,
					export_svg: true,
					export_pdf: true,
					modify_selection_attrs: true,
					modify_selection_mode: true,
					drill_to_anywhere: true,
					add_to_pulse: true,
					items: {
						create: true,
						delete: true,
						rename: true,
						modify: true,
						reorder: true,
						modify_type: true,
						modify_format: true,
						on_off: true,
						select_hierarchies: true,
					},
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						modify_layout: true,
						modify_type: true,
						modify_dashboard_filters: true,
						use_starred: true,
					},
					widgetViewOnly: false,
				},
				base: {
					isConsumer: false,
					isContributor: false,
					isAdmin: false,
					isSuper: true,
				},
			},
		},
		{
			title: 'Steven Sample ECommerce (3)',
			shares: [
				{
					shareId: '6095c108c59972001a487fa6',
					type: 'user',
				},
			],
			owner: {
				_id: '6095c108c59972001a487fa6',
				firstName: 'Test',
				lastName: 'Test',
				email: 'admin@sisense.com',
			},
			created: '2021-12-06T10:12:33.616Z',
			lastUpdated: '2021-12-06T10:12:33.616Z',
			instanceType: 'owner',
			oid: '61ade2116f928b00363f7993',
			allowChangeSubscription: false,
			datasource: {
				fullname: 'localhost/Sample ECommerce',
				id: 'localhost_aSampleIAAaECommerce',
				address: 'LocalHost',
				database: 'aSampleIAAaECommerce',
				live: false,
				title: 'Sample ECommerce',
			},
			lastOpened: null,
			lastPublish: '2021-08-10T21:21:09.667Z',
			parentFolder: null,
			userAuth: {
				dashboards: {
					create: true,
					delete: true,
					move: true,
					rename: true,
					duplicate: true,
					change_owner: true,
					toggle_edit_mode: true,
					edit_layout: true,
					edit_script: true,
					export_dash: true,
					export_jpeg: true,
					export_image: true,
					export_pdf: true,
					share: true,
					restore: true,
					copy_to_server: true,
					import: true,
					select_palette: true,
					replace_datasource: true,
					undo_import_dash: true,
					toggleDataExploration: true,
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						reorder: true,
						modify_type: true,
						toggle_auto_update: true,
						set_defaults: true,
						advanced: true,
						use_starred: true,
					},
				},
				widgets: {
					create: true,
					delete: true,
					rename: true,
					duplicate: true,
					copy_to_dashboard: true,
					edit: true,
					edit_script: true,
					change_type: true,
					export_csv: true,
					export_png: true,
					export_svg: true,
					export_pdf: true,
					modify_selection_attrs: true,
					modify_selection_mode: true,
					drill_to_anywhere: true,
					add_to_pulse: true,
					items: {
						create: true,
						delete: true,
						rename: true,
						modify: true,
						reorder: true,
						modify_type: true,
						modify_format: true,
						on_off: true,
						select_hierarchies: true,
					},
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						modify_layout: true,
						modify_type: true,
						modify_dashboard_filters: true,
						use_starred: true,
					},
					widgetViewOnly: false,
				},
				base: {
					isConsumer: false,
					isContributor: false,
					isAdmin: false,
					isSuper: true,
				},
			},
		},
		{
			title: 'Katherine healthcare',
			oid: '61b8f8c22914f00036ef5790',
			shares: [
				{
					shareId: '6095c108c59972001a487fa6',
					type: 'user',
				},
			],
			owner: {
				_id: '6095c108c59972001a487fa6',
				firstName: 'Test',
				lastName: 'Test',
				email: 'admin@sisense.com',
			},
			created: '2021-12-14T20:04:18.649Z',
			lastUpdated: '2021-12-14T20:04:21.625Z',
			instanceType: 'owner',
			lastOpened: '2021-12-15T08:46:01.650Z',
			datasource: {
				fullname: 'localhost/Sample Retail',
				id: 'localhost_aSampleIAAaRetail',
				address: 'LocalHost',
				database: 'aSampleIAAaRetail',
				live: false,
				title: 'Sample Retail',
			},
			userAuth: {
				dashboards: {
					create: true,
					delete: true,
					move: true,
					rename: true,
					duplicate: true,
					change_owner: true,
					toggle_edit_mode: true,
					edit_layout: true,
					edit_script: true,
					export_dash: true,
					export_jpeg: true,
					export_image: true,
					export_pdf: true,
					share: true,
					restore: true,
					copy_to_server: true,
					import: true,
					select_palette: true,
					replace_datasource: true,
					undo_import_dash: true,
					toggleDataExploration: true,
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						reorder: true,
						modify_type: true,
						toggle_auto_update: true,
						set_defaults: true,
						advanced: true,
						use_starred: true,
					},
				},
				widgets: {
					create: true,
					delete: true,
					rename: true,
					duplicate: true,
					copy_to_dashboard: true,
					edit: true,
					edit_script: true,
					change_type: true,
					export_csv: true,
					export_png: true,
					export_svg: true,
					export_pdf: true,
					modify_selection_attrs: true,
					modify_selection_mode: true,
					drill_to_anywhere: true,
					add_to_pulse: true,
					items: {
						create: true,
						delete: true,
						rename: true,
						modify: true,
						reorder: true,
						modify_type: true,
						modify_format: true,
						on_off: true,
						select_hierarchies: true,
					},
					filters: {
						create: true,
						delete: true,
						save: true,
						on_off: true,
						toggle_expansion: true,
						modify: true,
						modify_layout: true,
						modify_type: true,
						modify_dashboard_filters: true,
						use_starred: true,
					},
					widgetViewOnly: false,
				},
				base: {
					isConsumer: false,
					isContributor: false,
					isAdmin: false,
					isSuper: true,
				},
			},
		},
	],
	folders: [],
};

export default onlyDashboardsData;
